/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";
import {
  type CheckAndAssignReputation,
  checkAndAssignReputationBeet,
} from "../types/CheckAndAssignReputation";

/**
 * @category Instructions
 * @category CheckAndAssignReputation
 * @category generated
 */
export type CheckAndAssignReputationInstructionArgs = {
  checkAndAssignReputation: CheckAndAssignReputation;
};
/**
 * @category Instructions
 * @category CheckAndAssignReputation
 * @category generated
 */
export const CheckAndAssignReputationStruct = new beet.BeetArgsStruct<
  CheckAndAssignReputationInstructionArgs & {
    instructionDiscriminator: number;
  }
>(
  [
    ["instructionDiscriminator", beet.u8],
    ["checkAndAssignReputation", checkAndAssignReputationBeet],
  ],
  "CheckAndAssignReputationInstructionArgs"
);
/**
 * Accounts required by the _CheckAndAssignReputation_ instruction
 *
 * @property [_writable_, **signer**] reputationCheckerAcc
 * @property [_writable_] researcherProfilePdaAcc
 * @category Instructions
 * @category CheckAndAssignReputation
 * @category generated
 */
export type CheckAndAssignReputationInstructionAccounts = {
  reputationCheckerAcc: web3.PublicKey;
  researcherProfilePdaAcc: web3.PublicKey;
};

export const checkAndAssignReputationInstructionDiscriminator = 5;

/**
 * Creates a _CheckAndAssignReputation_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CheckAndAssignReputation
 * @category generated
 */
export function createCheckAndAssignReputationInstruction(
  accounts: CheckAndAssignReputationInstructionAccounts,
  args: CheckAndAssignReputationInstructionArgs,
  programId = new web3.PublicKey("C5M2JxBaxmsW62BgujPXEPytw65igtUjr6mFbD5pmypM")
) {
  const [data] = CheckAndAssignReputationStruct.serialize({
    instructionDiscriminator: checkAndAssignReputationInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.reputationCheckerAcc,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.researcherProfilePdaAcc,
      isWritable: true,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
