/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";
import {
  type CreateResearchePaper,
  createResearchePaperBeet,
} from "../types/CreateResearchePaper";

/**
 * @category Instructions
 * @category CreateResearchePaper
 * @category generated
 */
export type CreateResearchePaperInstructionArgs = {
  createResearchePaper: CreateResearchePaper;
};
/**
 * @category Instructions
 * @category CreateResearchePaper
 * @category generated
 */
export const CreateResearchePaperStruct = new beet.FixableBeetArgsStruct<
  CreateResearchePaperInstructionArgs & {
    instructionDiscriminator: number;
  }
>(
  [
    ["instructionDiscriminator", beet.u8],
    ["createResearchePaper", createResearchePaperBeet],
  ],
  "CreateResearchePaperInstructionArgs"
);
/**
 * Accounts required by the _CreateResearchePaper_ instruction
 *
 * @property [_writable_, **signer**] publisherAcc
 * @property [_writable_] researcherProfilePdaAcc
 * @property [_writable_] paperPdaAcc
 * @property [] systemProgramAcc
 * @category Instructions
 * @category CreateResearchePaper
 * @category generated
 */
export type CreateResearchePaperInstructionAccounts = {
  publisherAcc: web3.PublicKey;
  researcherProfilePdaAcc: web3.PublicKey;
  paperPdaAcc: web3.PublicKey;
  systemProgramAcc: web3.PublicKey;
};

export const createResearchePaperInstructionDiscriminator = 1;

/**
 * Creates a _CreateResearchePaper_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateResearchePaper
 * @category generated
 */
export function createCreateResearchePaperInstruction(
  accounts: CreateResearchePaperInstructionAccounts,
  args: CreateResearchePaperInstructionArgs,
  programId = new web3.PublicKey("C5M2JxBaxmsW62BgujPXEPytw65igtUjr6mFbD5pmypM")
) {
  const [data] = CreateResearchePaperStruct.serialize({
    instructionDiscriminator: createResearchePaperInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.publisherAcc,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.researcherProfilePdaAcc,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.paperPdaAcc,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgramAcc,
      isWritable: false,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
