/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";
import {
  type CreateResearcherProfile,
  createResearcherProfileBeet,
} from "../types/CreateResearcherProfile";

/**
 * @category Instructions
 * @category CreateResearcherProfile
 * @category generated
 */
export type CreateResearcherProfileInstructionArgs = {
  createResearcherProfile: CreateResearcherProfile;
};
/**
 * @category Instructions
 * @category CreateResearcherProfile
 * @category generated
 */
export const CreateResearcherProfileStruct = new beet.FixableBeetArgsStruct<
  CreateResearcherProfileInstructionArgs & {
    instructionDiscriminator: number;
  }
>(
  [
    ["instructionDiscriminator", beet.u8],
    ["createResearcherProfile", createResearcherProfileBeet],
  ],
  "CreateResearcherProfileInstructionArgs"
);
/**
 * Accounts required by the _CreateResearcherProfile_ instruction
 *
 * @property [_writable_, **signer**] researcherAcc
 * @property [_writable_] researcherProfilePdaAcc
 * @property [] systemProgramAcc
 * @category Instructions
 * @category CreateResearcherProfile
 * @category generated
 */
export type CreateResearcherProfileInstructionAccounts = {
  researcherAcc: web3.PublicKey;
  researcherProfilePdaAcc: web3.PublicKey;
  systemProgramAcc: web3.PublicKey;
};

export const createResearcherProfileInstructionDiscriminator = 0;

/**
 * Creates a _CreateResearcherProfile_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateResearcherProfile
 * @category generated
 */
export function createCreateResearcherProfileInstruction(
  accounts: CreateResearcherProfileInstructionAccounts,
  args: CreateResearcherProfileInstructionArgs,
  programId = new web3.PublicKey("C5M2JxBaxmsW62BgujPXEPytw65igtUjr6mFbD5pmypM")
) {
  const [data] = CreateResearcherProfileStruct.serialize({
    instructionDiscriminator: createResearcherProfileInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.researcherAcc,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.researcherProfilePdaAcc,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgramAcc,
      isWritable: false,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
