/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";
import {
  type MintResearchPaper,
  mintResearchPaperBeet,
} from "../types/MintResearchPaper";

/**
 * @category Instructions
 * @category MintResearchPaper
 * @category generated
 */
export type MintResearchPaperInstructionArgs = {
  mintResearchPaper: MintResearchPaper;
};
/**
 * @category Instructions
 * @category MintResearchPaper
 * @category generated
 */
export const MintResearchPaperStruct = new beet.FixableBeetArgsStruct<
  MintResearchPaperInstructionArgs & {
    instructionDiscriminator: number;
  }
>(
  [
    ["instructionDiscriminator", beet.u8],
    ["mintResearchPaper", mintResearchPaperBeet],
  ],
  "MintResearchPaperInstructionArgs"
);
/**
 * Accounts required by the _MintResearchPaper_ instruction
 *
 * @property [_writable_, **signer**] readerAcc
 * @property [_writable_] researcherProfilePdaAcc
 * @property [_writable_] researchMintCollectionPdaAcc
 * @property [_writable_] paperPdaAcc
 * @property [_writable_] feeReceiverAcc
 * @property [] systemProgramAcc
 * @category Instructions
 * @category MintResearchPaper
 * @category generated
 */
export type MintResearchPaperInstructionAccounts = {
  readerAcc: web3.PublicKey;
  researcherProfilePdaAcc: web3.PublicKey;
  researchMintCollectionPdaAcc: web3.PublicKey;
  paperPdaAcc: web3.PublicKey;
  feeReceiverAcc: web3.PublicKey;
  systemProgramAcc: web3.PublicKey;
};

export const mintResearchPaperInstructionDiscriminator = 4;

/**
 * Creates a _MintResearchPaper_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category MintResearchPaper
 * @category generated
 */
export function createMintResearchPaperInstruction(
  accounts: MintResearchPaperInstructionAccounts,
  args: MintResearchPaperInstructionArgs,
  programId = new web3.PublicKey("C5M2JxBaxmsW62BgujPXEPytw65igtUjr6mFbD5pmypM")
) {
  const [data] = MintResearchPaperStruct.serialize({
    instructionDiscriminator: mintResearchPaperInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.readerAcc,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.researcherProfilePdaAcc,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.researchMintCollectionPdaAcc,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.paperPdaAcc,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.feeReceiverAcc,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgramAcc,
      isWritable: false,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
