/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
export type MintResearchPaper = {
  metaDataMerkleRoot: string
  pdaBump: number
}

/**
 * @category userTypes
 * @category generated
 */
export const mintResearchPaperBeet =
  new beet.FixableBeetArgsStruct<MintResearchPaper>(
    [
      ['metaDataMerkleRoot', beet.utf8String],
      ['pdaBump', beet.u8],
    ],
    'MintResearchPaper'
  )
