/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
/**
 * @category enums
 * @category generated
 */
export enum PaperState {
  AwaitingPeerReview,
  InPeerReview,
  ApprovedToPublish,
  RequiresRevision,
  Published,
  Minted,
}

/**
 * @category userTypes
 * @category generated
 */
export const paperStateBeet = beet.fixedScalarEnum(
  PaperState
) as beet.FixedSizeBeet<PaperState, PaperState>
